version: "3.7"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/pure-data-update
    env_file:
      - ./.env
    environment: 
      - PASS=${PASS}
      - HEROKU_EMAIL=${HEROKU_EMAIL}
      - HEROKU_PASS=${HEROKU_PASS}
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444